name: Publish Package
on:
  push:
    branches: [main]
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Get current package version, clean it and set to envvar
        run: echo "PKG_VERSION="$(node -p "require('./package.json').version.match(/^(\d+\.)?(\d+\.)?(\*|\d+)/g)[0]") >> $GITHUB_ENV
      - name: Install Package
        run: npm install
      - name: Build
        run: npm build
      - name: Remove src Directory
        run: rm -rf src
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ ENV.PKG_VERSION }}
          bodyFile: "docs/release/v${{ ENV.PKG_VERSION }}.md"
          token: ${{ secrets.GITHUB_TOKEN }}